name: Build and Deploy

on:
  push:
    branches: [$default-branch]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build and Deploy
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          angular_dist_build_folder: dist/browser
          base_href: /${{ github.event.repository.name }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
